### ISSUE TITLE
Crash & Restart

### ISSUE THREAD

**Issue by Diavolo3045** [moxis/CryptoSight-Public#3]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.74
Comment: https://keybase.io/crypto

wcFMA4UdkFzzm+AhAQ//UvHoy8n/o91db5ta4zCe5QgpeXJU/HT/HdCAdpKYwGLA
t1awGwjyXoIk2AkE6G9mPtjiH6IDnKEbaztGzVTRPdEAAUeLKfXMjqNnV4RYuT0t
eUwhCoSgLM5BuIVd+lhYO3MoIQt5RTa2Jg2L8W8CS36ItWhnKOo38aRVpWZjjxSI
vubsfz15ssrh66LmizW0QmVSghtkR+jAdFr5O4CWGiQVF8E49mvEoyXmQGv1AQ02
C9JGwWS8efbC5O3fYfm28Isce1uYRqCTMK40qMMHYEmj1iDdKRahp9ZsEOrEneuX
71NuTqcSaT7TnMr6uEGpMaaDQhZaj/Zk1VEcfy8zNjh5hEk2P+YCPh/0Tnz+dCnk
LSxigi0R76B49nQubwwr7kQKzQx/rFCzE81aiwM9zsdWI67fx+ItB3TFZVMSVEqu
rCfr1aEAAWnmkVmSIY1gyaC6Djz1JRy2ZJsUIZ8BtC5MLFwp6m04N0br0CNp28gu
1bF/BI8kVwAx7LU0wa1cSKea39AdSXuWe8tjSQRSv2MVxgx4NKJTDOAB3tmqMcRG
kx74bFCXMiwXVPtvl6KdPAmdIkzWqnrr2v2It/CbqfcXWql+3+zoCN4gV9YfBlLF
uyxEpUne+veCW9WjbB9/cf7OqYaQ5+1D1nWXbx94ECEi7l6UvgNC06tCaQh8uBHB
wEwDcrj2u4Lx6cUBB/9gKoSg5Qsa6H5/0Fh3+HYl2z/O09YIoT1NRYvqr6q9vPbG
kwN9zT0RLZS7t/YDz4eKSs07LBNReeXIpx/MbFqcBkH5W80c80J7MUi+rnvUolCV
H5B04SnHLVAWvJ8jF8A27Y66/JMaYDzbuhkoIuy9I0COnCgmYNTncmdcBW4xNmpR
bfqk5eDbcDfxizHxOZhur1r1yc9HHAIF8Nhfn7t0pWygFG4fT6Jt2o3nN7bbXJyW
TsvvSvyxZl8AtohWB782qGJaFEc89GOy6LM5zaZy71ahH0XD4yL9J6awRc6z6QQ6
GtyYwMi351Rr7/4+AMU12KWPHDgbGY75ONtrmy1a0sGSAdo9XqIzy7o38nWjVogv
zU6AobHX20xdWmLuE/QuTRHMy8z/2KgAmTbTsfOlnrlZsvB126nZCxTvQlcOCd3o
bBUbujdHl6s3NySKT0JPAURliunDsGbK0/C3cUyxoUMPoWmsnYPxXKSYmDVrjOnz
Lllc0b8bRr1wF7KLa4LKr2bQ3WGbWZ6jBUPQtA/Iiqe80Qap2DwLobIXlVnbWhkC
Zad9h5LfpOGNaHhPytsJ+aF3M4yIhmJz3JOhAQE3U3wlPN4Dkfwq4mA6IuBtCRiI
EK8sciUSdon6iXzU2ntdRWwPj9jHqnJr8sPl2pkW6aoJZJkoJaPwnHX0LDcY56sl
8/Z7NLB8QRSIlaHEdn4ZC3NXeON5yvHhN0UnwEvtzCWShuT6+9Fh64AwZXPcBqmz
M4BEeRgIy5NB35QTvytnOge6R2hjBHPnWA9flyBpAI4CQyD/aNt8w3ZqYxZz9h1V
YqIkyOUfsVBnkhvgnZKHFoliMebT0yntN0sGBGeFhQ4LWEUm0/dFFYSoz21vox+S
dxkSNivO/pkQFHx35HrbFz0TWOSL0dQ9KSl4RpGkW1XnXox79L5zeOC3phT1hhzs
dczTBys69oeeAt6ZcY/Z8UzGtiPCJRRJArrwgjqbcdCmMyr6SgSlfm9I3dtxUlm7
qj3b+ljEueLwta8IzGpa8VhVmiuDGJuSdXiSDgjP77bRHX2ff+PIn6eFQ7uav4Ce
UP4Qnya4Rs7/aEUyi3+Dk7Gjj9dfOKqajf2DNgBKw0w+FAQ63u9Rh0SkpQoub8sN
9kCA
=323I
-----END PGP MESSAGE-----

**Comment by moxis** [comment]
Implemented.
