### ISSUE TITLE
Update Cryptosight Server Side Implementation

### ISSUE THREAD

**Issue by Diavolo3045** [moxis/CryptoSight-Public#4]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.74
Comment: https://keybase.io/crypto

wcFMA4UdkFzzm+AhAQ//cKLlZbKer224B7BouUShOowOPb4+vZ4FpzSaZtsBzsyh
gceW0Sbo70xjuTGxLPINasJEjDSVGKiaH3CCvkHEDpJq3FQEw2Wa/Jy4nxEwUSc4
M6y35RpVZ1JsR1vS8hgMh7+1YErPZzBKPbX9ahY19gI9eSb4PKuV6Ct2kKgGVZqM
1ljBIyigX+TthwCdpsAxrRxhougHu0rOka8M+2Jz+fs92+HsBxpgJ3IcPEfiCR1b
qHEyCOEBS7z1Z6f8msXMpl6h8qOg54AzWeq2rEow0Ab77sCAKyd8danVAI/eW2ZZ
uVtJwVbUujQw4JCWreRDlzwGznA59C4pb+1+5+jI82KliT+IHushIRqpJwLgeXGr
Sf4GrO0ceY9K/BiLyIMtqeLf3Q/JpQBV1h5eOWYUnvrzPms9MrvbVNAw5lYgpKOJ
E8pFswAD6KL0THVBqb+gPXG15sEazVc2/+7Jg/IfS7F2+m5y4oX/Z0/xmpAthcNQ
PoPg0EKhm6zkTc0guImBQ2O4jP/8XTUhKfkqQgVxOXf8giNS98LnKOoTIrP1y4L2
14EQxd6frTmJG85SP2NA2PNhOZwvIJ05lq8Xu43xm/KTOvClf1R+7Uh09Z16jL/7
ifOXd6YeU8M9JYLt0IaktJqk29tnoxt7MHoCUkVfiovdFUHf0W9F/WEHye/rWNXB
wEwDcrj2u4Lx6cUBB/4zan9dsr6A1Y5MTsC5anNM1fxDJPd0LHVo2rUB1w0M65kg
X9Ze7jeHgv15QoABiDltVY55+kv0lctyRgFRlTSsRWeYqG8uA4WrQaPcLXVWcN8O
v7O06/zBHLXrJ+SrsLIQL1kkt0l8I8UveZlmOu9cGdrLHV5Fd6sao+/B3H5ev5dw
R9vQIPyyIyvb+Rk69Lz0Z+uwZCSSX95rKdASiYnwvztgonMW0XMeM5QoPY36Akg1
o0WhtmCdRikjrDSu5kbY+JFdH90e/J8+sdfqr6rfkx4dirIM0g5BCED/1feA5QnQ
JrFZ1xLfasS4utAyepQXvTR96vcC/SNvyEAhyLvL0sIVAQGEAj9c8v06yicF5tHN
2WyCx625WR7pFgMiHCKgqh4+BitcRtZgy7PKdhs0AjmS3RZ41DKaQ4PkIGpUB6aE
4nM3A/wBfyyGl/EICQTnBre+roVUV3g/oYNBDC8La2SKplUoSewj9x2uuLMzQ00I
v8P7hVolyzzqsLXwnvpbxu/1kvTg7lgyH3Nw+1BFcJKjS0J1KI9G5AOmMI+Z0eXn
nlve6NnZzg+qmOnHq/4VWTBKTFaho8J7zlSHekXV8cgnU7WtlXHVzco/3dUKNHBL
qtvVrAb5tBnmAJ145FUoxm3/IFh6dZADuCMrL3AYHtigsnD9ptr3UIqv+uHcEW7X
H6YXw4gx0FLgjYv9YOoGA097lFSHERS5xjlH8XXyPSAjUE3VgYDtnkOFrvkuVD4B
2VM8iMqsBCWyVliHm6aayfdkXYgYiP7P/Pcuc/6jR2ewagXNHdglHD1Gf9mEgB3G
XO+czjGLS7QUoyDJWBmY0yQw9Kfzn4e6jr15Wxxf+ji7WY4/vz4P52iid1yHgA4p
33SyOwmbgZ4FmAhTZF3/kJnlWT3zhzMyUbrxyOrG8l9Owi64NQNCXvv9Fva3AloC
xWuFuN5N4+nCTJ5P1TT/T4cHzj1GfOowO/xNtJiQPjhgVwAMKPV8w1LpsPSOOHuh
y+/1RFPV+MJ9FqV91vyBhzYlHJI5BujMnypl+ELoWsREuthU3fDqiwuVfANdU0+R
SzQBvYTONCwuHwa1r4uvHQkDOEbI8KETEkN2BxCqq8f/n3d+oE0ib4GBGkwedrex
53zEMxy158FWzsz48JkiTur0+sUk83Wqk3lsGNsXzWH3Glyk8jpCKY+ZARCawUMI
gWMrU2PFu3A91qoV6YXOwFcpMovZRFioQm7vprvQlcL8V6R5CgHwr8/4Nuoh3Cgq
DjqfEptIyZsTbfARsPXaBcR6+1rpL95/7kTGKNA9ZIdtn6TldF4=
=o1kR
-----END PGP MESSAGE-----

**Comment by moxis** [comment]
Implemented
