### ISSUE TITLE
API Connection Issues - Bittrex

### ISSUE THREAD

**Issue by Diavolo3045** [moxis/CryptoSight-Public#7]
Neil Donnelly, [13.10.17 16:29]
API Connection issues. Please try again later.

Neil Donnelly, [13.10.17 16:29]
Intermittently

Neil Donnelly, [13.10.17 16:29]
Was fine earlier

Dante, [13.10.17 16:29]
poloniex?

Neil Donnelly, [13.10.17 16:29]
Bittrex

Timeframe 
Was set to 24h

**Comment by moxis** [comment]
That's an issue from Bittrex servers. No need to freak out when it happens like once or twice. Just run the command again :)
